import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="globallayout">

        <Link href="/">
            <button>home</button>
          </Link>

          <Link href="/Assignment-1">
            <button>Assignment-1</button>
          </Link>


          <Link href="/Assignment-2">
            <button>Assignment-2</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
