import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="globallayout">

        <Link href="/">
            <button>home</button>
          </Link>

          <Link href="/Assignment-1">
            <button>Assignment-1</button>
          </Link>

          <Link href="/Assignment-2">
            <button>Assignment-2</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
