import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="ass-1layout">
          <Link href="/Assignment-1/Question1">
            <button>Question-1</button>
          </Link>
          <Link href="/Assignment-1/Question2">
            <button>Question-2</button>
          </Link>
          <Link href="/Assignment-1/Question3">
            <button>Question-3</button>
          </Link>
          <Link href="/Assignment-1/Question4">
            <button>Question-4</button>
          </Link>
          <Link href="/Assignment-1/Question5">
            <button>Question-5</button>
          </Link>
          <Link href="/Assignment-1/Question6">
            <button>Question-6</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
